twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        contact_address: '120 Allée Plein Ciel'
        contact_city: 'Ville'
        contact_email: 'prenom.nom@domaine.fr'
        contact_phone: '01.23.45.67.89'
        contact_zip: '12345'
        copyright: 'Copyright © 2021 - Odile GIRGIEL'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
